[package]
name = "constellation-server"
version = "0.0.1"
description = "Pluggable authoritative DNS server. Entries can be added & removed from an HTTP REST API."
readme = "README.md"
license = "MPL-2.0"
homepage = "https://github.com/valeriansaliou/constellation"
repository = "https://github.com/valeriansaliou/constellation.git"
keywords = ["dns", "api"]
categories = ["web-programming"]
authors = ["Valerian Saliou <valerian@valeriansaliou.name>"]

[badges]
travis-ci = { repository = "valeriansaliou/constellation", branch = "master" }
coveralls = { repository = "valeriansaliou/constellation", branch = "master", service = "github" }

[[bin]]
name = "constellation"
path = "src/main.rs"
doc = false

[dependencies]
log = "0.4"
toml = "0.4"
clap = { version = "2.26", default-features = false }
lazy_static = "1.0"
serde = "1.0"
serde_derive = "1.0"
r2d2 = "0.8"
r2d2_redis = "0.7"
redis = "0.8"

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true

[profile.release]
opt-level = "s"
lto = true
debug = false
debug-assertions = false
